- name: Play1  
  hosts: all                        # groupName in the inventory file 
  tasks: 
    - name: Printing Hai from task1 of play1
      ansible.builtin.debug:
        msg: "Hai from task1 of play1"

    - name: Printing Hai from task2 of play1
      ansible.builtin.debug:
        msg: "DevOps from batch55 of play1"

- name: Play2  
  hosts: all                        # groupName in the inventory file 
  tasks: 
    - name: Printing Hai from task1 of play2
      ansible.builtin.debug:
        msg: "Olaaaaaaaaaaaaaa : task1 from play2"
        